### PR TITLE
Project setup. [(Finishes) #158938644]

### PR DESCRIPTION
**Pull request by ibetween**
### What does this PR do?
This PR has required **files** and **directories** for the **Thriller diary**
### Description
The following files have been added to the project:

- index.html - will be the homepage
- sign-up.html - will help users to create an account
- sign-in.html - will help users to sign in into their accounts
- modify.html - will help users to add or edit a diary entry
-  diaries.html - will help users to see a list of their diary entries
- content.html - user will view the content of a diary entry here.

### How to access the project locally?
- Make sure you have [chrome browser](https://www.google.com/chrome/) installed. 
- Configure [web-server-chrome](https://github.com/kzahel/web-server-chrome)
- Clone the repository for this project into your local machine:
```
git clone https://github.com/james-chege/thriller-diary.git
```
- open the webserver and set current directory to UI (_which is a sub-directory of the cloned project_)

### Requirement
- HTML5 and CSS3

__pivotal tracker Story Id__
- [#158938644](https://www.pivotaltracker.com/story/show/158938644)

### CODE REVIEW

**Comment by YAHYA-H** [comment]
its nice kinda seem so!

**Comment by YAHYA-H** [comment]
but i would really have liked to see the screenshot if not gh-pages
plus you got no .gitignore file please add it cos i think we doing it in Virtual environment and  we are going to be building on this template

**Comment by YAHYA-H** [comment]
and also please do each feature on a different branch okay

**Comment by ibetween** [comment]
Alright. Thanks a lot. Will add the .gitignore file immediately. Also will add screenshots on the next pr and do each feature on separate branchs. Thanks :heart:

**Comment by YAHYA-H** [comment]
and also i will send you  git branch naming system on the slack now follow it to so that you can create a good git branch names ..it will help you brah

**Comment by YAHYA-H** [comment]
[GIT branch naming system](https://allenan.com/git-branch-naming-conventions/l)

**Pull request merged**
